version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    versioning-strategy: "lockfile-only"
    groups:
      dependencies:
        patterns:
          - "*" # Update all packages together
    cooldown:
      include:
        - '*'
      default-days: 7
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      include:
        - '*'
      default-days: 7
